---
services:
  code-server:
    image: linuxserver/code-server:arm32v7-4.14.1
    container_name: code-server
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - PWA_APPNAME=code-server #optional
      # - EXTENSIONS_GALLERY= {"serviceUrl":"https://marketplace.visualstudio.com/vscode","itemUrl":"https://marketplace.visualstudio.com/vscode"}
    volumes:
      - /code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
