version: "3.8"
services:
  sub-store:
    image: xream/sub-store:latest
    container_name: sub-store
    network_mode: host
    restart: always
    volumes:
      - /mnt/sda3/sub-store-data:/opt/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - SUB_STORE_BACKEND_CRON=0 0 * * *
      - SUB_STORE_FRONTEND_BACKEND_PATH=/1234567890
      - SUB_STORE_FRONTEND_HOST=0.0.0.0
      - SUB_STORE_FRONTEND_PORT=3001
      - SUB_STORE_DATA_BASE_PATH=/opt/app/data
      - SUB_STORE_BACKEND_API_HOST=0.0.0.0
      - SUB_STORE_BACKEND_API_PORT=3002
    stdin_open: true
    tty: true
